### ISSUE TITLE
Design Review - Entity List

### ISSUE THREAD

**Issue by nazlikaya** [camunda-cloud/common-ui#28]
- [ ] Type of the entity icon color : #62626E   https://zpl.io/Vqq5qMN
- [ ] Type of the entity icon should have bigger margin than how it is implemented (even if there is no checkbox) - https://zpl.io/Vqq5qMN
- [x] Hover state of the entity is missing  https://zpl.io/Vqq5qMN
- [x] While the entity list is scrolling, the title area and column header will be sticky and only entities will be scrollable. https://zpl.io/a8gvg6E
- [x] The loading backdrop should cover everything except the list title. Currently, it is not a problem not to block column titles as they are not actionable but once we have sorting we have to block that area. That’s why I would suggest doing it now.
https://zpl.io/VYvnvZn

**Comment by alexandertrefz** [comment]
The Icon Color and width of the icon column are concerns for the implementation on the App-side, in this case console.

As for the color: I have updated all the icons we had with the versions that you have shared via the Drive Folder, the exact icon you shared is being used. 

The hover state and loading state for the column headers is fixed in the current beta. Column titles are already actionable, sorting is implemented on the common-ui side (but may not be enabled on every entity list within console).

The scrolling situation will be looked at at a later date.
